--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Atomization/Depot
branches:
  - master
projects:
  Depot:
    path: ""
    libs:
      - src: "atom/gui"
        version: "^1.0.1"
...
