--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Atomization/Depot
branches:
  - master
projects:
  Depot:
    path: ""
    libs:
      - src: https://github.com/Atomization/gui/releases/download/1.0.1/gui.phar
...
